services:
  db:
    restart: always
    image: postgres
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_PASSWORD: 123
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5444:5432"
  api:
    build: .
    ports:
      - 8080:8080
    command: "yarn start:prod"
    depends_on:
      - db

volumes:
  db-data:
